# Simulation constants
ACTIVE_THRESHOLD = 40.0
SIMULATION_DURATION = 20
N_PREDATORS = 3
N_PREYS = 2 * N_PREDATORS
INITIAL_GRASS = 500.0

# Prey constants
PREY_INIT_ENERGY = 50.0
PREY_ENERGY_LOSS = 5.0
PREY_GRASS_EAT = 20.0
PREY_REPRODUCTION_THRESHOLD = 65.0

# Predator constants
PREDATOR_INIT_ENERGY = 60.0
PREDATOR_ENERGY_LOSS = 8.0
PREDATOR_PREY_EAT = 20.0
PREDATOR_KILL_PROBABILITY = 1
PREDATOR_REPRODUCTION_THRESHOLD = 70.0
